# Site
name: "Sana REKBI's Blog"
title: "Sana REKBI - Web Development & Tutorials"
description: "A personal blog showcasing web development projects, tutorials, and insights."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "" # Laisser vide si le site est à la racine du dépôt GitHub Pages
google_analytics: "" # Remplace par ton ID Google Analytics si nécessaire
disqus: "" # Supprimer ou ajouter ton identifiant Disqus si tu veux des commentaires
mailchimp-list: "" # Supprime cette ligne si tu n'utilises pas Mailchimp
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sana:
    name: Sana REKBI
    display_name: Sana REKBI
    avatar: 'assets/images/avatar.png' # Ajoute une image de profil ici
    email: sana.rekbi@example.com
    web: https://github.com/sana-rekbi 
    twitter: https://twitter.com/sana_rekbi 
    description: "Web developer and AI enthusiast sharing projects and tutorials on web development, AI, and data science."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (désactivé ici, supprime si inutile)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Exclusions (fichiers qui ne doivent pas être inclus dans le site)
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
