# Site
name: "Sana REKBI Blog"
title: "Sana REKBI - Web Development & Tutorials"
description: "A blog showcasing my web development projects, tutorials, and insights."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "" # Laisser vide pour GitHub Pages ou Netlify
google_analytics: "" # Ajoute ton propre ID Google Analytics si nécessaire
disqus: "" # Si tu utilises Disqus, ajoute ton identifiant ici
mailchimp-list: "" # Supprimé car probablement inutile dans ton cas
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sana:
    name: Sana REKBI
    display_name: Sana REKBI
    gravatar: # Tu peux ajouter un identifiant gravatar si nécessaire
    email: sana.rekbi@example.com
    web: https://github.com/sana-rekbi
    twitter: https://twitter.com/sana_rekbi
    description: "Web developer and AI enthusiast sharing projects and tutorials on web development, AI, and data science."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (désactivé par défaut)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Exclusions
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

